# Generated by Django 5.1.2 on 2025-01-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fn', models.CharField(max_length=20)),
                ('ln', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
            ],
        ),
    ]
