# Generated by Django 5.1.2 on 2025-01-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='fn',
            new_name='first name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ln',
            new_name='last name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='mailid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='password',
        ),
    ]
