# Generated by Django 5.1.2 on 2025-01-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_dob_users_dob_rename_fn_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last name',
            new_name='last_name',
        ),
    ]
