# Generated by Django 5.1.2 on 2025-01-22 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
